version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - ireturn
    - lll
    - maintidx
    - mnd
    - nlreturn
    - nonamedreturns
    - testpackage
    - varnamelen
    - wsl
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - forcetypeassert
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
